version: "3"

services:

  ### TEST GROUP
  ###
  stellar-test:
    image: stellar/quickstart
    restart: always
    environment:
      - NETWORK=testnet
      - POSTGRES_PASSWORD=$TESTNET_PASS
      - ENABLE_ASSET_STATS=true
    volumes:
      - ./opt/stellar-test:/opt/stellar
    ports:
      - 3001:8000

  postgraphile-core-test:
    # build: ./postgraphile
    image: tyvdh/postgraphile
    restart: always
    environment:
      WAIT_HOSTS: stellar-test:5432
      WAIT_BEFORE_HOSTS: 10
      WAIT_AFTER_HOSTS: 10
      USER: stellar
      PASS: $TESTNET_PASS
      HOST: stellar-test
      PORT: 5432
      DB: core
    ports:
      - 4001:5000
    depends_on:
      - stellar-test

  postgraphile-horizon-test:
    # build: ./postgraphile
    image: tyvdh/postgraphile
    restart: always
    environment:
      WAIT_HOSTS: stellar-test:5432
      WAIT_BEFORE_HOSTS: 10
      WAIT_AFTER_HOSTS: 10
      USER: stellar
      PASS: $TESTNET_PASS
      HOST: stellar-test
      PORT: 5432
      DB: horizon
    ports:
      - 5001:5000
    depends_on:
      - stellar-test
  ###
  ### END TEST GROUP

  ### LIVE GROUP
  ###
  stellar:
    image: stellar/quickstart
    restart: always
    environment:
      - NETWORK=pubnet
      - POSTGRES_PASSWORD=$PUBNET_PASS
      - ENABLE_ASSET_STATS=true
    volumes:
      - ./opt/stellar:/opt/stellar
    ports:
      - 3000:8000

  postgraphile-core:
    # build: ./postgraphile
    image: tyvdh/postgraphile
    restart: always
    environment:
      WAIT_HOSTS: stellar:5432
      WAIT_BEFORE_HOSTS: 10
      WAIT_AFTER_HOSTS: 10
      USER: stellar
      PASS: $PUBNET_PASS
      HOST: stellar
      PORT: 5432
      DB: core
    ports:
      - 4000:5000
    depends_on:
      - stellar

  postgraphile-horizon:
    # build: ./postgraphile
    image: tyvdh/postgraphile
    restart: always
    environment:
      WAIT_HOSTS: stellar:5432
      WAIT_BEFORE_HOSTS: 10
      WAIT_AFTER_HOSTS: 10
      USER: stellar
      PASS: $PUBNET_PASS
      HOST: stellar
      PORT: 5432
      DB: horizon
    ports:
      - 5000:5000
    depends_on:
      - stellar
  ###
  ### END LIVE GROUP
